# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_lspm <- function(y_tr, X_tr, X_ts) {
    .Call(`_ConformalIDR_fit_lspm`, y_tr, X_tr, X_ts)
}

fit_olspm <- function(y_tr, X_tr, X_ts) {
    .Call(`_ConformalIDR_fit_olspm`, y_tr, X_tr, X_ts)
}

cidr_sequential <- function(x_r, x_out, w, W, w_out, pos_x, y_unique_r, y_out, n_thr, n_x) {
    .Call(`_ConformalIDR_cidr_sequential`, x_r, x_out, w, W, w_out, pos_x, y_unique_r, y_out, n_thr, n_x)
}

cidr_static <- function(x_r, x_out, w, W, w_out, pos_x, y_unique_r, y_out, n_thr, n_x) {
    .Call(`_ConformalIDR_cidr_static`, x_r, x_out, w, W, w_out, pos_x, y_unique_r, y_out, n_thr, n_x)
}

